In [3]:
 import numpy as np


In [5]:
arr = np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [9]:
type(arr)

numpy.ndarray

In [11]:
arr.ndim

1

In [13]:
arr.dtype

dtype('int32')

In [15]:
array_new = np.array([1,2,3,4,5,6])

In [17]:
array_new + 3

array([4, 5, 6, 7, 8, 9])

In [19]:
import numpy as np

my_numpy_array = np.array([1, 2, 3, 4, 5])


In [21]:
new_arr=my_numpy_array*3

In [23]:
new_arr

array([ 3,  6,  9, 12, 15])

In [25]:
type(my_numpy_array)

numpy.ndarray

In [27]:
1

1

In [29]:
array_new

array([1, 2, 3, 4, 5, 6])

In [31]:
array_new * 2

array([ 2,  4,  6,  8, 10, 12])

In [33]:
import numpy as np

my_array = np.array([1, 2, 3])
result = my_array * 2
print(result)  


[2 4 6]


In [35]:
arr

array([1, 2, 3, 4])

In [37]:
arr>2

array([False, False,  True,  True])

In [45]:

   import numpy as np

   list_data = [1, 2, 3, 4, 5]
   array_from_list = np.array(list_data)

In [47]:
list_data

[1, 2, 3, 4, 5]

In [49]:
type(list_data)

list

In [51]:
list_data

[1, 2, 3, 4, 5]

In [53]:
type(array_from_list)

numpy.ndarray

In [55]:
array_from_list.dtype

dtype('int32')

In [57]:
lis1 = [1,2,3,4,5]

In [59]:
arr

array([1, 2, 3, 4])

In [61]:
arr.mean()

2.5

In [65]:
import numpy as np

array1 = np.array([1,2,3])



In [67]:
   import numpy as np

   zeros_array = np.zeros((3, 3))     

In [69]:
   ones_array = np.ones((2, 4))        


In [71]:
   identity_matrix = np.eye(3)      
    

In [73]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
   random_array = np.random.rand(4, 4) 

In [77]:
l = [1,2,3,4]

In [79]:
np.array(l,dtype=np.int32 )

array([1, 2, 3, 4])

In [87]:

   import numpy as np

   range_array = np.arange(0, 10, 2)      
   linspace_array = np.linspace(0, 10, 5)  


In [89]:
linspace_array

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [91]:
linspace_array_2 = np.linspace(0, 10, 6)
linspace_array_2


array([ 0.,  2.,  4.,  6.,  8., 10.])

In [93]:
linspace_array_3=np.linspace(0,15,4)

In [95]:
linspace_array_3

array([ 0.,  5., 10., 15.])

In [97]:
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)



In [99]:
array_from_list

array([1, 2, 3, 4, 5])

In [101]:
tuple_data = (5.5, 6.6, 7.7)
array_from_tuple = np.array(tuple_data)

In [103]:
zeros_array = np.zeros((3, 3))      
ones_array = np.ones((2, 4))       
identity_matrix = np.eye(3)         

random_array = np.random.rand(4, 4) 

In [105]:
random_array

array([[0.25335701, 0.36036975, 0.94520208, 0.69133186],
       [0.7707356 , 0.07394816, 0.05597156, 0.473714  ],
       [0.80737487, 0.66376474, 0.54181028, 0.30115174],
       [0.1960526 , 0.0292467 , 0.66523144, 0.53253216]])

In [107]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [109]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [111]:

import numpy as np

a1 = np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [115]:
np.array([10,20,30,40],dtype=float)

array([10., 20., 30., 40.])

In [117]:

np.arange(0,11)         


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
np.arange(16).reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [121]:
(1,2)
(3,2,1)

(3, 2, 1)

In [123]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [127]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [129]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [131]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [133]:
np.random.random((3,4))

array([[0.63093472, 0.8336115 , 0.52794896, 0.94034137],
       [0.24133324, 0.19589684, 0.4198035 , 0.0478103 ],
       [0.62809514, 0.07096   , 0.02924286, 0.95911626]])

In [135]:
np.random.random((3,5))

array([[0.75261946, 0.15822528, 0.76732258, 0.0512298 , 0.8230548 ],
       [0.72195724, 0.50414416, 0.92219516, 0.60963506, 0.44248482],
       [0.74027814, 0.90474428, 0.31570258, 0.09003549, 0.70446629]])

In [137]:
np.linspace(-20,20,20,dtype=int)

array([-20, -18, -16, -14, -12, -10,  -8,  -6,  -4,  -2,   1,   3,   5,
         7,   9,  11,  13,  15,  17,  20])

In [139]:

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [142]:
1

1

In [144]:
l.append(5)

In [146]:
1

1

In [148]:
a11 = np.arange(12)
a22 = np.arange(12).reshape(3,4)
a33 = np.arange(27).reshape(3,3,3)

In [151]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [153]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
a11.ndim

1

In [157]:
a22.ndim

2

In [159]:
a33.ndim

3

In [161]:
import numpy as np
array_1d = np.array([1, 2, 3])
array_1d.ndim  

1

In [163]:

array_2d = np.array([[1, 2], [3, 4]])
array_2d.ndim 

2

In [165]:
a11.shape

(12,)

In [167]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [169]:
a22.shape

(3, 4)

In [171]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
a33.shape

(3, 3, 3)

In [175]:
array_1d.shape

(3,)

In [177]:
array_2d.shape  

(2, 2)

In [179]:
a11.size

12

In [181]:
a22.size

12

In [183]:
a22.shape

(3, 4)

In [185]:
a33.shape

(3, 3, 3)

In [187]:
array_1d.size 

3

In [189]:

array_2d.size  


4

In [191]:
a11.dtype

dtype('int32')

In [193]:
import numpy as np
array1 = np.array([10, 20, 30, 40])

array2 = np.array([15, 20, 25, 50])

In [195]:
array1 > 15

array([False,  True,  True,  True])

In [197]:
array2 < 30

array([ True,  True,  True, False])

In [199]:
True and False 

False

In [201]:
array1 > 15

array([False,  True,  True,  True])

In [203]:
array2 < 30

array([ True,  True,  True, False])

In [207]:
array = np.linspace(0, 10,4 )
array

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [209]:
a = np.arange(24)

In [211]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [213]:
a = np.arange(24).reshape(6,4)


In [215]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [217]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = np.reshape(array, (2, 3))
reshaped_array  


array([[1, 2, 3],
       [4, 5, 6]])

In [221]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

In [223]:
splits = np.hsplit(array, 2)

print(splits)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [225]:
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [227]:
np.hsplit(array,4)

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [229]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

splits = np.vsplit(array, 3)

print(splits)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [233]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


In [235]:
splits = np.vsplit(array, 3)

print(splits)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [237]:
   import numpy as np

   arr = np.array([1, 2, 3, 4, 5])
   arr[2] = 99  


In [239]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr[1:4] = 0  # Update elements at indices 1, 2, and 3 to 0


In [241]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mask = arr > 2
arr[mask] = 99  


In [243]:
arr

array([ 1,  2, 99, 99, 99])

In [245]:
arr> 80

array([False, False,  True,  True,  True])

In [247]:
arr[arr>80] =0

In [249]:
arr

array([1, 2, 0, 0, 0])